Repository SweetBrothers/sweetbrothers, pull requests merged in 2023-11, with the labels that each got.

#1 readme.md 수정
  README.md
Labels: documentation

#29 그라디오앱의 전체적인 틀 추가
  2주차/gradio/REAME.md
  2주차/gradio/gradio_test.py
  2주차/gradio/requirement.txt
Labels: Priority: High, Status: Completed, Type: Enhancement

#32 Fix : Yolo Crop
  1주차/Yolo_Crop/crop.py
  2주차/gradio/README.md
Labels: Priority: Critcal, Status: Completed, Type: Bug

#33 3주차 flask api 및 gradio 구현
  3주차/Flask_api/main.py
  3주차/Flask_api/requirement.txt
  3주차/Gradio_app/main.py
  3주차/Gradio_app/reqiurement.txt
  3주차/README.MD
Labels: Priority: High, Status: Completed, Type: Enhancement
